mqtt:
  broker: "192.168.1.100"
  username: ha
  password: [YOUR PASSWORD HERE]
  top_dir_name: garage  # used as MQTT top directory
Sensors:
  Maximintegrated_DS18B20:
  - path: /sys/bus/w1/devices/28-011939f0e24a/w1_slave
    mqtt_sub_dir: cistern
  - path: /sys/bus/w1/devices/28-01193a05774d/w1_slave
    friendly: Outside
  Generic_PulseCounter:
  - pin_number: 23
    mqtt_sub_dir: garden
    function: water-flow  
  - pin_number: 24
    mqtt_sub_dir: home
    function: water-flow
  TexasInstruments_INA219_4_20mA:  
  - address: 0x40
    mqtt_sub_dir: citern
    mqtt_function_name: height   # or Current...
    channel: 1                   # path: "/dev/i2c-1"    
    shunt_resistor: 9.78         # 10 Ohm : measure it for the best results or buy a 0.1% resistor ; choose a value between 6 and 14 ohm for the best results.
    calibration_low_mA:  4.00    #  4mA
    calibration_high_mA: 20.0    # 20mA
    full_range_value:  5000      # 5 mm = 20mA         0m = 4mA
    unit: mm                     # meter  




 
