mqtt:
  broker: "192.168.1.100"
  username: ha
  password: [YOUR PASSWORD HERE]
  top_dir_name: garage  # used as MQTT top directory
Sensors:
  LINUX_Maximintegrated_DS18B20:
  - path: /sys/bus/w1/devices/28-011939f0e24a/w1_slave
    mqtt_sub_dir: cistern
  - path: /sys/bus/w1/devices/28-01193a05774d/w1_slave
    friendly: Outside
  RPI_Generic_PulseCounter:
  - pin_number: 23
    mqtt_sub_dir: garden
    function: water-flow  
    scale_factor: 1
  - pin_number: 24
    mqtt_sub_dir: home
    function: water-flow
    scale_factor: 1
  LINUX_TexasInstruments_INA219_4_20mA:  
  - address: 0x40
    mqtt_sub_dir: citern
    mqtt_function_name: height   # or Current...
    channel: 1                   # path: "/dev/i2c-1"   => channel 1 
    shunt_resistor: 9.78         # max. 16 Ohm for full range 4-20mA :   buy a 0.1% resistor or measure it for the best results; choose a value between 9 and 16 ohm for the best results.
    calibration_low_mA:  4.00    #  4mA
    calibration_high_mA: 20.0    # 20mA
    full_range_value:  5000      # 5 mm = 20mA         0m = 4mA
    unit: mm                     # meter  




 
