#!/bin/bash

#  This file is part of the sensors2mqtt distribution (https://github.com/DCL777/sensors2mqtt.git).
#  Copyright (c) 2020 Dries Claerbout 
#  
#  This program is free software: you can redistribute it and/or modify  
#  it under the terms of the GNU General Public License as published by  
#  the Free Software Foundation, version 3.
#  
#  This program is distributed in the hope that it will be useful, but 
#  WITHOUT ANY WARRANTY; without even the implied warranty of 
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU 
#  General Public License for more details.
#  
#  You should have received a copy of the GNU General Public License 
#  along with this program. If not, see <http://www.gnu.org/licenses/>.

sudo apt update
sudo apt upgrade
sudo apt install git
sudo apt-get install i2c-tools    
sudo apt-get install python-smbus 
sudo adduser pi i2c               
#sudo reboot                       
sudo apt install python3-rpi.gpio
sudo apt-get install python3 
sudo apt-get install python3-pip
git clone https://github.com/DCL777/sensors2mqtt.git
cd sensors2mqtt
sudo pip3 install -r requirements.txt
cd sensors2mqtt
chmod 777 ./sensors2mqtt.py
./sensors2mqtt.py