mqtt:
  broker: "192.168.1.100"
  username: ha
  password: [YOUR PASSWORD HERE]
  top_dir_name: garage  # used as MQTT top directory
Sensors:
  RPI_Generic_PulseCounter:
  - pin_number: 23
    mqtt_sub_dir: garden
    function: water-flow  
  - pin_number: 24
    mqtt_sub_dir: home
    function: water-flow
