name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.7","3.8", "3.9", "3.10"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install system dependencies
      run: |
        sudo apt-get update -y
        sudo apt-get install libcurl4-openssl-dev libgnutls28-dev libssl-dev uuid-dev
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
        pip3 install -r requirements.txt
    - name: Analysing the code with pylint
      run: |
        # pylint $(git ls-files '*.py')
        pylint --disable=C0301,C0103,R0902 --extension-pkg-whitelist=pycurl $(git ls-files '*.py')
